// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEQR6-oNe8sJ07a4oER9t74b03AzHeZ3U',
    appId: '1:183116732639:web:adcd59f10985583c69f16a',
    messagingSenderId: '183116732639',
    projectId: 'taskmanager-bc372',
    authDomain: 'taskmanager-bc372.firebaseapp.com',
    storageBucket: 'taskmanager-bc372.appspot.com',
    measurementId: 'G-RFNH7MWETP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg7L4S0-TNdv-q6HFUAZpbnVyVlOOlNKc',
    appId: '1:183116732639:android:770f15731b860b6b69f16a',
    messagingSenderId: '183116732639',
    projectId: 'taskmanager-bc372',
    storageBucket: 'taskmanager-bc372.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd1FIWOmCKU9gvMUrzw0l8M6aTp_n44Es',
    appId: '1:183116732639:ios:b4051ed1ca70cb0769f16a',
    messagingSenderId: '183116732639',
    projectId: 'taskmanager-bc372',
    storageBucket: 'taskmanager-bc372.appspot.com',
    iosBundleId: 'com.example.taskmanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd1FIWOmCKU9gvMUrzw0l8M6aTp_n44Es',
    appId: '1:183116732639:ios:b4051ed1ca70cb0769f16a',
    messagingSenderId: '183116732639',
    projectId: 'taskmanager-bc372',
    storageBucket: 'taskmanager-bc372.appspot.com',
    iosBundleId: 'com.example.taskmanager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEQR6-oNe8sJ07a4oER9t74b03AzHeZ3U',
    appId: '1:183116732639:web:68726be3b7414bf769f16a',
    messagingSenderId: '183116732639',
    projectId: 'taskmanager-bc372',
    authDomain: 'taskmanager-bc372.firebaseapp.com',
    storageBucket: 'taskmanager-bc372.appspot.com',
    measurementId: 'G-YJ37ERY33B',
  );

}